# Generated by Django 4.2 on 2024-03-01 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bacon", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Score",
        ),
    ]
