# Generated by Django 4.2 on 2024-01-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bacon", "0002_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="query",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
